# fly.toml app configuration file generated for minecraftserver-qqfzq on 2025-11-07T07:55:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minecraftserver-qqfzq'
primary_region = 'iad'

[build]

[[mounts]]
  source = 'server'
  destination = '/server'

[http_service]
  internal_port = 25565
  force_https = true
  protocol = tcp
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
