app = "MinecraftServer"
primary_region = "sin"

[env]
  JAVA_TOOL_OPTIONS = "-Xmx256M -Xms256M"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1

  [[services.ports]]
    port = 25565
