app = "MinecraftServer"

primary_region = "sin"  # or change to "iad", "fra", etc.

[build]
  dockerfile = "Dockerfile"

[env]
  JAVA_TOOL_OPTIONS = "-Xmx1024M -Xms1024M"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 1
  auto_stop_machines = false

  [[services.ports]]
    port = 25565
