app = "fly-minecraft-samuel"
primary_region = "sin"  # Change to your closest region

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 25565
  protocol = "tcp"
  auto_start_machines = true
  min_machines_running = 1
  auto_stop_machines = false

  [[services.ports]]
    port = 25565
